/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_swofty_nativebridge_NativeParser */

#ifndef _Included_net_swofty_nativebridge_NativeParser
#define _Included_net_swofty_nativebridge_NativeParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_swofty_nativebridge_NativeParser
 * Method:    parseSwoftLang
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_swofty_nativebridge_NativeParser_parseSwoftLang
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_swofty_nativebridge_NativeParser
 * Method:    parseSwoftLangToCommands
 * Signature: (Ljava/lang/String;)[Lnet/swofty/nativebridge/representation/Command;
 */
JNIEXPORT jobjectArray JNICALL Java_net_swofty_nativebridge_NativeParser_parseSwoftLangToCommands
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
