# WardenSK
# Adds support for all Warden (entity) related things
# Recommended:
    # Skript 2.14+
    # Skript-Reflect 2.6.3+
    # SkBee 3.20+
    # Paper 1.21.10+
# Apologies for any inconsistencies, WardenSK is a solo project, which means it is bound to have errors.

# Lusk Warden Syntax .sk Port
# Although, few syntaxes may not function identical to Lusk.

import:
    org.bukkit.entity.Entity

# _       __               __               
#| |     / /___ __________/ /__  ____  _____
#| | /| / / __ `/ ___/ __  / _ \/ __ \/ ___/
#| |/ |/ / /_/ / /  / /_/ /  __/ / / (__  ) 
#|__/|__/\__,_/_/   \__,_/\___/_/ /_/____/  

#    ______                               _                 
#   / ____/  ______  ________  __________(_)___  ____  _____
#  / __/ | |/_/ __ \/ ___/ _ \/ ___/ ___/ / __ \/ __ \/ ___/
# / /____>  </ /_/ / /  /  __(__  |__  ) / /_/ / / / (__  ) 
#/_____/_/|_/ .___/_/   \___/____/____/_/\____/_/ /_/____/  
#          /_/                                              

# Warden - Anger (Don't get this confused with Skript's Warden Anger Level, that expression is towards a entity, this one is general anger.)
# Gets the anger level of this warden. Anger is an integer from 0 to 150. Once a Warden reaches 80 anger at a target it will actively pursue it.

expression:
    patterns:
        [the] anger of %entity% [(specific: (for %entity%))]
        %entity%'[s] anger [(specific: (for %entity%))]
    return type: integer
    get:
        if expr-2 is set:
            return expr-1.getAnger(expr-2)
        else if expr-2 is not set:
            return expr-1.getAngerLevel()
    set:
        expr-2 is set:
            expr-1.setAnger(expr-2, change value)
    add:
        expr-2 is set:
            expr-1.increaseAnger(expr-2, change value)
    reset:
        expr-2 is set:
            expr-1.clearAnger(expr-2)

# Warden - (Prey)
# Returns the entity at which this warden is most angry.

expression:
    patterns:
        [the] prey of %entity%
        %entity%'[s] prey
    return type: livingEntity
    get:
        expr-1 = warden
        return expr-1.getEntityAngryAt()
    set:
        expr-1.setAnger(change value)
    remove: 
        entity.clearAnger(change value)

# Warden - Angry State
# Returns the Angry State of an entity.
# (Warden, PigZombie, Wolf, Enderman)
# Can be set for all except wardens.

expression:
    patterns:
        [the] ang(ry|er) state of %entity%
        %entity%'[s] ang(ry|er) state
        whether %entity% is angry [or not]
        whether [or not] %entity% is angry
    return type: boolean
    get:
        if expr-1 is angry:
            return true
        else if expr-1 isn't angry:
            return false

# Warden Anger (Event)
# Returns the past/future anger of the warden in the Warden Anger Change event.
# The future anger level can be set.

expression:
    patterns:
        [the] [future: future|past: past] anger [level] [of [the] warden]
    return type: integer
    usable in:
        WardenAngerChangeEvent
    get:
        if first element of parse tags is not set:
            return the anger of (event.getEntity())
        else if the first element of parse tags contains "future":
            return {-futureAnger::%(event.getEntity())%}
            delete {-futureAnger::%(event.getEntity())%}
        else if the first element of parse tags contains "future":
            return {-pastAnger::%(event.getEntity())%}
            delete {-pastAnger::%(event.getEntity())%}
    set:
        event.getEntity().setNewAnger(change value)

# Warden - Highest Anger Level || NOT IN LUSK
# Anger is an integer from 0 to 150. Once a Warden reaches 80 anger at a target it will actively pursue it.

expression:
    patterns:
        [the] highest anger [level] of %livingEntity%
        %livingEntity%'s highest anger [level]
    return type: integer
    get:
        return expr-1.getHighestAnger()

# Warden - Is Angry (Property)

expression:
    patterns:
        [the] [is] angry of %livingentities%
        %livingentities%'[s] [is] angry
    return type: boolean
    get:
        return whether expr-1 is angry

#    ______________          __      
#   / ____/ __/ __/__  _____/ /______
#  / __/ / /_/ /_/ _ \/ ___/ __/ ___/
# / /___/ __/ __/  __/ /__/ /_(__  ) 
#/_____/_/ /_/  \___/\___/\__/____/  

# Warden - Disturb
# Makes a warden sense a disturbance at the provided location.

effect:
    patterns:
        disturb %livingentities% from %location%
    trigger:
        expr-1 = warden
        expr-1.setDisturbanceLocation(expr-2)

#   ______                ___ __  _                 
#  / ____/___  ____  ____/ (_) /_(_)___  ____  _____
# / /   / __ \/ __ \/ __  / / __/ / __ \/ __ \/ ___/
#/ /___/ /_/ / / / / /_/ / / /_/ / /_/ / / / (__  ) 
#\____/\____/_/ /_/\__,_/_/\__/_/\____/_/ /_/____/  

# Warden - Is Agitated
# Checks if a Warden is agitated.

condition:
    patterns:
        %livingentities% (is|are|=) agitated
        %livingentities% (negative:(isn't|is not|aren't|are not|!=)) agitated
    check:
        if first element of parse tags contains "negative":
            loop exprs-1:
                if expr-1's anger is between 40 and 79:
                    stop
                continue
        else if first element of parse tags is not set:
            loop exprs-1:
                if expr-1's anger isn't between 40 and 79:
                    stop
                continue

# Warden - Is Angry
# Checks if a Warden is agitated.

condition:
    patterns:
        %livingentities% (is|are|=) angry
        %livingentities% (negative:(isn't|is not|aren't|are not|!=)) angry
    check:
        if first element of parse tags contains "negative":
            loop exprs-1:
                if expr-1's anger is between 80 and 150:
                    stop
                continue
        else if first element of parse tags is not set:
            loop exprs-1:
                if expr-1's anger isn't between 80 and 150:
                    stop
                continue

# Warden - Is Calm
# Checks if a Warden is calm.

condition:
    patterns:
        %livingentities% (is|are|=) calm
        %livingentities% (negative:(isn't|is not|aren't|are not|!=)) calm
    check:
        if first element of parse tags contains "negative":
            loop exprs-1:
                if expr-1's anger is between 0 and 39:
                    stop
                continue
        else if first element of parse tags is not set:
            loop exprs-1:
                if expr-1's anger isn't between 0 and 39:
                    stop
                continue

#    ______                 __      
#   / ____/   _____  ____  / /______
#  / __/ | | / / _ \/ __ \/ __/ ___/
# / /___ | |/ /  __/ / / / /_(__  ) 
#/_____/ |___/\___/_/ /_/\__/____/  

# On Warden - On Anger Change

import:
    io.papermc.paper.event.entity.WardenAngerChangeEvent

event "On Warden - On Anger Change":
    patterns:
        [on] warden anger chang(e[d]|ing)
    event-values: command sender, entity, entity type, location, world

on WardenAngerChangeEvent:
    set {_eventValues::commandSender} to event.getTarget()
    set {_eventValues::entity} to event.getEntity()
    set {_eventValues::entityType} to event.getEntityType()
    set {_eventValues::location} to event.getEntity()'s location
    set {_eventValues::world} to world of (event.getEntity()'s location)
    set {_event} to (custom event "On Warden - On Anger Change" using event-values {_eventValues::*})
    call {_event}
    if {_event}.isCancelled():
        cancel event
        event.setCancelled(true)
    set {-pastAnger::%event.getEntity()%} to event.getOldAnger()
    set {-futureAnger::%event.getEntity()%} to event.getNewAnger()

# On Warden - On Sniff Toggle

import:
    org.bukkit.event.entity.EntityPoseChangeEvent

event "On Warden - on Sniff Toggle": # When using IntelliSkript, highlights/colors may not show.
    patterns:
        [on] warden (start:(sniff[ing] [start|begin]|start sniffing))
        [on] warden (stop:(sniff[ing] stop|stop sniffing))
        [on] warden (sniff toggle|toggle sniff)
    event-values: command sender, entity, entity type, location, pose, world, pose
    check:
        first element of parse tags is set
        if first element of parse tags contains "start":
            if pose != sniffing_pose:
                stop
            continue
        else if first element of parse tags contains "stop":
            if pose = sniffing_pose:
                stop
            continue

on entity pose change: # You need SkBee 3.20+
    event-entity = warden
    if any:
        event-pose = sniffing_pose
        past event-pose = sniffing_pose
    then:
        set {_eventValues::commandSender} to event-commandSender
        set {_eventValues::entity} to event-entity
        set {_eventValues::entityType} to event-entityType
        set {_eventValues::location} to event-location
        set {_eventValues::pose::pose} to event-pose
        set {_eventValues::world} to event-world
        set {_eventValues::pose::pastPose} to past event-pose
        set {_event} to (custom event "On Warden - on Sniff Toggle" using event-values {_eventValues::*})
        call {_event}