/*
 * SwoftLang language server (LSP over Node IPC).
 *
 * Features:
 *   - Diagnostics: debounced `swoftc check` of the live buffer via a temp file.
 *   - Completion : keywords + declarations + operators + types + constants +
 *                  builtins + event names + property names (context-light).
 *   - Hover      : builtins (signature + doc) and properties (owner + type).
 *   - Document symbols: command / event / function / gui / scoreboard /
 *                  tablist / bossbar / mob / item declarations.
 *
 * The compiler prints `file:line:col: error|warning: msg` on stderr and
 * `{"error":{"message","line","col"}}` on stdout. line/col are 1-based; LSP
 * positions are 0-based, so we subtract one (clamped at 0).
 */
import {
  createConnection,
  ProposedFeatures,
  TextDocuments,
  TextDocumentSyncKind,
  InitializeResult,
  Diagnostic,
  DiagnosticSeverity,
  CompletionItem,
  CompletionItemKind,
  Hover,
  MarkupKind,
  DocumentSymbol,
  SymbolKind,
  Range,
  Position,
} from 'vscode-languageserver/node';
import { TextDocument } from 'vscode-languageserver-textdocument';
import {
  createCompletionEngine,
  braceDepth,
  collectLocals,
  findEnclosingPacketClass,
  PacketData,
} from './completion';
import { spawn } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { fileURLToPath } from 'url';

// --- symbol data (bundled, generated by scripts/gen-symbols.js) ---
interface Symbol {
  name: string;
  kind: string;
  signature?: string;
  signatures?: string[];
  doc?: string;
  owner?: string;
  type?: string;
  writable?: boolean;
}
interface SymbolData {
  symbols: Symbol[];
  enums: Record<string, string[]>;
}

function loadSymbols(): SymbolData {
  const candidates = [
    path.join(__dirname, '..', '..', 'data', 'swoftlang-symbols.json'), // out/src -> pkg/data
    path.join(__dirname, '..', 'data', 'swoftlang-symbols.json'),
  ];
  for (const p of candidates) {
    try {
      return JSON.parse(fs.readFileSync(p, 'utf8')) as SymbolData;
    } catch {
      /* try next */
    }
  }
  return { symbols: [], enums: {} };
}
const symbolData = loadSymbols();

// --- packet catalog (bundled, generated by scripts/gen-packets.js) ---
function loadPackets(): PacketData {
  const candidates = [
    path.join(__dirname, '..', '..', 'data', 'packets.json'), // out/src -> pkg/data
    path.join(__dirname, '..', 'data', 'packets.json'),
  ];
  for (const p of candidates) {
    try {
      return JSON.parse(fs.readFileSync(p, 'utf8')) as PacketData;
    } catch {
      /* try next */
    }
  }
  return { packets: {} };
}
const packetData = loadPackets();

// --- settings ---
interface Settings {
  swoftcPath: string;
  scriptsDir: string;
}
let settings: Settings = { swoftcPath: '', scriptsDir: '' };
let workspaceRoot: string | undefined;

const connection = createConnection(ProposedFeatures.all);
const documents = new TextDocuments(TextDocument);

connection.onInitialize((params): InitializeResult => {
  const folders = params.workspaceFolders;
  if (folders && folders.length > 0) {
    try {
      workspaceRoot = fileURLToPath(folders[0].uri);
    } catch {
      /* ignore */
    }
  } else if (params.rootUri) {
    try {
      workspaceRoot = fileURLToPath(params.rootUri);
    } catch {
      /* ignore */
    }
  }
  const init = params.initializationOptions as Partial<Settings> | undefined;
  if (init) settings = { ...settings, ...init };

  return {
    capabilities: {
      textDocumentSync: TextDocumentSyncKind.Incremental,
      completionProvider: { triggerCharacters: ['.', '<', ':'] },
      hoverProvider: true,
      documentSymbolProvider: true,
    },
  };
});

connection.onDidChangeConfiguration((change) => {
  const cfg = (change.settings as any)?.swoftlang;
  if (cfg) {
    settings.swoftcPath = cfg.swoftcPath ?? settings.swoftcPath;
    settings.scriptsDir = cfg.scriptsDir ?? settings.scriptsDir;
  }
  // re-check all open docs
  for (const doc of documents.all()) scheduleValidation(doc);
});

// --- swoftc resolution: setting -> SWOFTC env -> `swoftc` on PATH -> workspace default ---
function resolveSwoftc(): string {
  if (settings.swoftcPath && settings.swoftcPath.trim()) return settings.swoftcPath.trim();
  if (process.env.SWOFTC && process.env.SWOFTC.trim()) return process.env.SWOFTC.trim();
  if (workspaceRoot) {
    const local = path.join(workspaceRoot, 'compiler', '_build', 'default', 'bin', 'main.exe');
    if (fs.existsSync(local)) return local;
  }
  return 'swoftc';
}

function addonPath(): string | undefined {
  if (!workspaceRoot) return undefined;
  const p = path.join(workspaceRoot, 'addons');
  return fs.existsSync(p) ? p : undefined;
}

// --- diagnostics ---
const debounceTimers = new Map<string, NodeJS.Timeout>();

function scheduleValidation(doc: TextDocument, delay = 300): void {
  const prev = debounceTimers.get(doc.uri);
  if (prev) clearTimeout(prev);
  debounceTimers.set(
    doc.uri,
    setTimeout(() => {
      debounceTimers.delete(doc.uri);
      void validate(doc);
    }, delay),
  );
}

// stderr:  file:line:col: error|warning: message
const DIAG_RE = /^(.*?):(\d+):(\d+):\s*(error|warning):\s*(.*)$/;

function clampPos(line: number, col: number): Position {
  return Position.create(Math.max(0, line - 1), Math.max(0, col - 1));
}

function underlineRange(doc: TextDocument, pos: Position): Range {
  // Extend to the end of the current identifier/token for a visible squiggle.
  const text = doc.getText();
  const offset = doc.offsetAt(pos);
  let end = offset;
  while (end < text.length && /[A-Za-z0-9_]/.test(text[end])) end++;
  if (end === offset) end = Math.min(text.length, offset + 1);
  return Range.create(pos, doc.positionAt(end));
}

async function validate(doc: TextDocument): Promise<void> {
  const text = doc.getText();
  const bin = resolveSwoftc();

  // write the live buffer to a temp file that keeps a .sw extension
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'swoftlang-'));
  const base = path.basename(uriToFsPath(doc.uri) || 'buffer.sw');
  const tmpFile = path.join(tmpDir, base.endsWith('.sw') ? base : base + '.sw');
  fs.writeFileSync(tmpFile, text);

  const args = ['check', tmpFile];
  const ap = addonPath();
  if (ap) args.push('--addon-path', ap);

  const diags: Diagnostic[] = [];
  try {
    const { stdout, stderr } = await runSwoftc(bin, args);

    for (const rawLine of stderr.split(/\r?\n/)) {
      const m = DIAG_RE.exec(rawLine.trim());
      if (!m) continue;
      const [, , lineStr, colStr, sev, msg] = m;
      const pos = clampPos(parseInt(lineStr, 10), parseInt(colStr, 10));
      diags.push({
        severity: sev === 'warning' ? DiagnosticSeverity.Warning : DiagnosticSeverity.Error,
        range: underlineRange(doc, pos),
        message: msg,
        source: 'swoftc',
      });
    }

    // stdout JSON: {"error":{"message","line","col"}} — belt-and-suspenders in
    // case the machine channel reports an error the stderr line did not.
    const trimmed = stdout.trim();
    if (trimmed.startsWith('{')) {
      try {
        const obj = JSON.parse(trimmed);
        if (obj && obj.error && typeof obj.error.message === 'string') {
          const pos = clampPos(Number(obj.error.line) || 1, Number(obj.error.col) || 1);
          const already = diags.some(
            (d) => d.range.start.line === pos.line && d.message === obj.error.message,
          );
          if (!already) {
            diags.push({
              severity: DiagnosticSeverity.Error,
              range: underlineRange(doc, pos),
              message: obj.error.message,
              source: 'swoftc',
            });
          }
        }
      } catch {
        /* not JSON, ignore */
      }
    }
  } catch (err: any) {
    // Only surface a spawn failure once, as an info-ish error on line 0.
    if (err && err.code === 'ENOENT') {
      diags.push({
        severity: DiagnosticSeverity.Warning,
        range: Range.create(0, 0, 0, 1),
        message: `swoftc not found (tried "${bin}"). Set swoftlang.swoftcPath or SWOFTC.`,
        source: 'swoftlang',
      });
    }
  } finally {
    try {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  }

  connection.sendDiagnostics({ uri: doc.uri, diagnostics: diags });
}

function runSwoftc(
  bin: string,
  args: string[],
): Promise<{ stdout: string; stderr: string; code: number | null }> {
  return new Promise((resolve, reject) => {
    const child = spawn(bin, args, { cwd: workspaceRoot });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (d) => (stdout += d.toString()));
    child.stderr.on('data', (d) => (stderr += d.toString()));
    child.on('error', reject);
    child.on('close', (code) => resolve({ stdout, stderr, code }));
  });
}

function uriToFsPath(uri: string): string | undefined {
  try {
    return fileURLToPath(uri);
  } catch {
    return undefined;
  }
}

documents.onDidChangeContent((e) => scheduleValidation(e.document));
documents.onDidOpen((e) => scheduleValidation(e.document, 0));
documents.onDidClose((e) => {
  const t = debounceTimers.get(e.document.uri);
  if (t) clearTimeout(t);
  debounceTimers.delete(e.document.uri);
  connection.sendDiagnostics({ uri: e.document.uri, diagnostics: [] });
});

// --- completion (context-aware, see completion.ts) ---
const engine = createCompletionEngine(symbolData, packetData);

connection.onCompletion((params): CompletionItem[] => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return [];
  const pos = params.position;
  const prefix = doc.getText({ start: Position.create(pos.line, 0), end: pos });
  const before = doc.getText({ start: Position.create(0, 0), end: pos });
  const depth = braceDepth(before);
  const locals = collectLocals(before);
  const ctx = engine.analyze(before);
  return engine.getCompletions(prefix, depth, locals, ctx);
});

connection.onCompletionResolve((item) => engine.resolve(item));

// --- hover ---
const symbolByName = new Map<string, Symbol[]>();
for (const s of symbolData.symbols) {
  const arr = symbolByName.get(s.name) || [];
  arr.push(s);
  symbolByName.set(s.name, arr);
}

function wordAt(doc: TextDocument, pos: Position): string | undefined {
  const text = doc.getText();
  const offset = doc.offsetAt(pos);
  let start = offset;
  let end = offset;
  while (start > 0 && /[A-Za-z0-9_]/.test(text[start - 1])) start--;
  while (end < text.length && /[A-Za-z0-9_]/.test(text[end])) end++;
  if (start === end) return undefined;
  return text.slice(start, end);
}

// Map a well-known receiver identifier (the `X` in `X.prop`) to its owner type,
// so hover can pick the right property owner instead of listing all of them.
const RECEIVER_OWNERS: Record<string, string> = {
  player: 'Player',
  sender: 'Player',
  location: 'Location',
  loc: 'Location',
  world: 'World',
  item: 'Item',
  mob: 'Mob',
  entity: 'Entity',
  server: 'Server',
};

function inferReceiverOwner(doc: TextDocument, pos: Position, word: string): string | undefined {
  const line = doc.getText({ start: Position.create(pos.line, 0), end: Position.create(pos.line, 1000) });
  const idx = line.indexOf(word);
  // find `<recv> . word` immediately before the hovered word
  const m = /([A-Za-z_][\w]*)\s*\.\s*$/.exec(line.slice(0, idx < 0 ? line.length : idx));
  if (!m) return undefined;
  return RECEIVER_OWNERS[m[1].toLowerCase()];
}

connection.onHover((params): Hover | null => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return null;
  const word = wordAt(doc, params.position);
  if (!word) return null;

  // Packet-aware hover: inside a `Packet { on "Class" { } }` handler, `packet`
  // shows the class and each `packet.<field>` shows its type. This wins over the
  // generic symbol table when we are demonstrably in a packet handler.
  const before = doc.getText({ start: Position.create(0, 0), end: params.position });
  const packetClass = findEnclosingPacketClass(before);
  if (packetClass) {
    const info = engine.getPacketInfo(packetClass);
    if (info) {
      if (word === 'packet') {
        const dir = info.direction === 'client' ? 'inbound (client)' : 'outbound (server)';
        const body =
          `**packet**: \`${packetClass}\` — ${dir}\n\n\`${info.fq}\`\n\n` +
          (info.fields.length
            ? info.fields.map((f) => `\`packet.${f.name}\`: \`${f.type}\``).join('  \n')
            : '_no fields_');
        return { contents: { kind: MarkupKind.Markdown, value: body } };
      }
      const field = engine.getPacketField(packetClass, word);
      if (field) {
        const jt = field.javaType ? `\n\n\`${field.javaType}\`` : '';
        return {
          contents: {
            kind: MarkupKind.Markdown,
            value: `\`${packetClass}.${field.name}\`: \`${field.type}\` _(read-only)_${jt}`,
          },
        };
      }
    }
  }

  const matches = symbolByName.get(word);
  if (!matches || matches.length === 0) return null;

  const lines: string[] = [];
  const builtin = matches.find((m) => m.kind === 'builtin');
  const evt = matches.find((m) => m.kind === 'event');
  const props = matches.filter((m) => m.kind === 'property');

  if (builtin) {
    lines.push('```swoftlang\n' + (builtin.signatures || [builtin.signature || word]).join('\n') + '\n```');
    if (builtin.doc) lines.push(builtin.doc);
  }
  if (evt) {
    lines.push(`**event ${evt.name}**`);
    if (evt.doc) lines.push(evt.doc);
  }
  if (props.length > 0) {
    // If we can tell what the receiver is (e.g. `player.<word>`), show just that
    // owner's property rather than every owner that happens to expose `word`.
    const preferred = inferReceiverOwner(doc, params.position, word);
    let shown = props;
    if (preferred) {
      const narrowed = props.filter((p) => p.owner === preferred);
      if (narrowed.length > 0) shown = narrowed;
    }
    lines.push(
      shown
        .map((p) => `\`${p.owner}.${p.name}\`: \`${p.type}\`${p.writable ? '' : ' _(read-only)_'}`)
        .join('  \n'),
    );
  }
  if (lines.length === 0) {
    const other = matches[0];
    lines.push(`**${word}** — ${other.kind}`);
    if (other.doc) lines.push(other.doc);
  }
  return { contents: { kind: MarkupKind.Markdown, value: lines.join('\n\n') } };
});

// --- document symbols ---
// A declaration keyword must be followed by a name/quote/brace — never by `:`
// (that would be a property key like `item: …`, not an `item` declaration).
const DECL_RE =
  /^\s*(command|event|async\s+function|function|gui|scoreboard|tablist|bossbar|server|storage|mob|item)\b(?!\s*:)(.*)$/;

function declSymbolKind(decl: string): SymbolKind {
  if (decl.startsWith('command')) return SymbolKind.Method;
  if (decl.startsWith('event')) return SymbolKind.Event;
  if (decl.includes('function')) return SymbolKind.Function;
  if (decl === 'gui') return SymbolKind.Struct;
  if (decl === 'scoreboard' || decl === 'tablist' || decl === 'bossbar') return SymbolKind.Interface;
  if (decl === 'server' || decl === 'storage') return SymbolKind.Namespace;
  if (decl === 'mob') return SymbolKind.Class;
  if (decl === 'item') return SymbolKind.Constant;
  return SymbolKind.Object;
}

// pull the declared name(s): "hello", 'tp', PlayerChat, doThing
function declName(rest: string): string {
  const s = rest.trim();
  const quoted = s.match(/["']([^"']+)["']/);
  if (quoted) return quoted[1];
  const ident = s.match(/^([A-Za-z_][A-Za-z0-9_]*)/);
  if (ident) return ident[1];
  return s.replace(/\{.*$/, '').trim() || '(anonymous)';
}

connection.onDocumentSymbol((params): DocumentSymbol[] => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return [];
  const text = doc.getText();
  const lines = text.split(/\r?\n/);
  const out: DocumentSymbol[] = [];
  for (let i = 0; i < lines.length; i++) {
    const m = DECL_RE.exec(lines[i]);
    if (!m) continue;
    const decl = m[1].replace(/\s+/g, ' ');
    let name = declName(m[2]);
    // Singleton declarations (`server {`, `storage {`) carry no name — label
    // them with the keyword itself instead of "(anonymous)".
    if (name === '(anonymous)' && (decl === 'server' || decl === 'storage')) name = decl;
    const range = Range.create(i, 0, i, lines[i].length);
    out.push({
      name,
      detail: decl,
      kind: declSymbolKind(decl),
      range,
      selectionRange: range,
    });
  }
  return out;
});

documents.listen(connection);
connection.listen();
